[package]
name = "cxm"
version = "0.0.1-beta.3"
description = "A Tauri App"
authors = ["worksoup"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cxm_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
chrono = "0.4"
# cxsign = { git = "https://github.com/worksoup/newsign.git" }
cxsign = { git = "https://github.com/worksoup/newsign.git", branch = "dev-v0.2" }
# cxsign = { path = "../../newsign/" }
env_logger = "0.11"
image = "0.25"
log = { version = "0.4", features = ["release_max_level_info"] }
percent-encoding = "2.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2.0.0-beta", features = [] }
tauri-plugin-barcode-scanner = "2.0.0-beta"
tauri-plugin-shell = "2.0.0-beta"
ureq = { version = "2.10", features = ["cookies", "json"] }
tauri-plugin-dialog = "2.0.0-beta"
xdsign_data = { git = "https://github.com/learturely/xdsign_data.git" }

[target.'cfg(any(target_os = "linux", target_os = "windows", target_os = "macos"))'.dependencies]
xcap = { version = "0.0.13" }

[profile.release]
panic = "abort"
codegen-units = 1
lto = "fat"
strip = "symbols"
